### ISSUE TITLE
About the halium-10.0-rebase branch

### ISSUE THREAD

**Issue by nitanmarcel** [Aarqw12/Atoll-11#2]
Hello. I'm glad you took interest in upstreaming this kernel and probably you can help improving it.

Is there a status for this kernel? Also you might want to merge the latest changes from the "official" repository since it adds a few things to the kernel configuration.

https://gitlab.com/ubports/community-ports/android10/xiaomi-redmi-note-9-pro/kernel-xiaomi-sm6250

The best thing to do is to use the same kernel maybe for rebase and make a PR there on gitlab?

Thanks.

**Comment by Aarqw12** [comment]
issue resolved see https://gitlab.com/ubports/community-ports/android10/xiaomi-redmi-note-9-pro/xiaomi-miatoll
